server:
  port: 8080

spring:
  application:
    name: ewm-main-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:6542/ewm}
    username: ${SPRING_DATASOURCE_USERNAME:ewm}
    password: ${SPRING_DATASOURCE_PASSWORD:ewm}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    ru.practicum: INFO